# Generated by Django 5.2.5 on 2025-09-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PoliceOfficer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("police_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile_no", models.CharField(max_length=15)),
                ("rank", models.CharField(blank=True, max_length=50, null=True)),
                ("station", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True)),
                ("longitude", models.FloatField(blank=True)),
                ("radius", models.FloatField(blank=True, help_text="Radius in meters")),
            ],
        ),
        migrations.CreateModel(
            name="ZoneType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_types",
                        to="dept.zone",
                    ),
                ),
            ],
            options={
                "ordering": ("zone", "name"),
                "unique_together": {("zone", "name")},
            },
        ),
        migrations.CreateModel(
            name="ZoneAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(blank=True)),
                ("end_time", models.TimeField(blank=True)),
                (
                    "risk_points",
                    models.PositiveIntegerField(
                        blank=True, default=0, help_text="Risk score between 0 and 100"
                    ),
                ),
                (
                    "zone_type",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="dept.zonetype",
                    ),
                ),
            ],
            options={
                "ordering": ("zone_type", "start_time"),
            },
        ),
    ]
