# Generated by Django 3.1.14 on 2025-09-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
