# Generated by Django 3.1.14 on 2025-09-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(help_text='Radius in meters')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('risk_points', models.PositiveIntegerField(default=0, help_text='Risk score between 0 and 100')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dept.zone')),
                ('zone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dept.zonetype')),
            ],
            options={
                'ordering': ['zone', 'zone_type', 'start_time'],
            },
        ),
    ]
