# Generated by Django 3.1.14 on 2025-09-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_zone_zonealert_zonetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonealert',
            options={'ordering': ('zone_type', 'start_time')},
        ),
        migrations.AlterModelOptions(
            name='zonetype',
            options={'ordering': ('zone', 'name')},
        ),
        migrations.RemoveField(
            model_name='zonealert',
            name='zone',
        ),
        migrations.AddField(
            model_name='zonetype',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zone_types', to='dept.zone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='zonetype',
            unique_together={('zone', 'name')},
        ),
    ]
