# Generated by Django 5.2.5 on 2025-09-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dept", "0003_auto_20250901_2240"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zonetype",
            name="description",
        ),
    ]
