# Generated by Django 5.2.5 on 2025-09-23 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 24, 0, 22, 13, 512570)
            ),
        ),
    ]
