# Generated by Django 5.2.5 on 2025-09-23 10:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0002_tourist_blood_group_tourist_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 23, 15, 32, 22, 213241)
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="tourist",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to="tourist.tourist",
            ),
        ),
    ]
