# Generated by Django 5.2.5 on 2025-09-23 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0002_alter_apikey_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourist",
            name="password",
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 24, 0, 49, 24, 19851)
            ),
        ),
    ]
