# Generated by Django 3.1.14 on 2025-09-24 17:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_alter_apikey_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='password',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 22, 41, 24, 870662)),
        ),
        migrations.CreateModel(
            name='ClusterMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tourist.cluster')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_members', to='tourist.touristlocation')),
            ],
        ),
    ]
