# Generated by Django 5.2.5 on 2025-09-23 10:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0003_alter_apikey_created_at_alter_otp_tourist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 23, 15, 36, 20, 941100)
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="tourist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to="tourist.tourist",
            ),
        ),
        migrations.AlterField(
            model_name="tourist",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tourist",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
