# Generated by Django 5.2.5 on 2025-09-23 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist", "0004_alter_apikey_created_at_alter_otp_tourist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourist",
            name="aadhaar_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 23, 15, 50, 47, 88405)
            ),
        ),
    ]
